services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Pipirima\PimcoreFtpExportBundle\Service\Logger:
        arguments:
            - '%pimcore_ftp_export.debug%'

    Pipirima\PimcoreFtpExportBundle\Service\MailerService: ~
    Pipirima\PimcoreFtpExportBundle\Service\MailFactory: ~
    Pipirima\PimcoreFtpExportBundle\Service\WebsiteSettingsService: ~
    Pipirima\PimcoreFtpExportBundle\Service\StringService: ~
    Pipirima\PimcoreFtpExportBundle\Service\ConfigService:
        arguments:
            - '%pimcore_ftp_export.exports%'

    Pipirima\PimcoreFtpExportBundle\EventHandler\AssetEventHandler:
        tags:
            - { name: kernel.event_listener, event: pimcore.asset.postAdd, method: onAssetPostAdd }
